name: 01-Caching
on: 
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  determine_variables:
    runs-on: ubuntu-24.04
    outputs:
      nuget_package: ${{ steps.setupNuget.outputs.NUGET }}
    steps:
    - name: Setup NuGet
      id: setupNuget
      run: echo "NUGET=${{github.workspace}}/.nuget/packages" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
  
  build:
    needs: [determine_variables]
    runs-on: ubuntu-24.04
    env:
      NUGET_PACKAGES: ${{ needs.determine_variables.outputs.nuget_package }}
    steps:    
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
        dotnet-quality: 'ga'

    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: ${{env.NUGET_PACKAGES}}
        key: ${{runner.os}}-build-${{ hashFiles('**/packages.lock.json', '!**/bin/**', '!**/obj/**') }}

    - name: Dotnet restore
      run: dotnet restore --locked-mode --nologo
    
    - name: Dotnet build
      run: dotnet build --no-restore --configuration Release
